version: '3'
services:
  express-application:
    build: .
    ports:
     - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/app
    command: npm run dev
    depends_on:
      - super-mongo
  super-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongoose
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
    